[package]
name = "wei-log"
version = "0.2.2"
edition = "2021"
description = "wei log"
documentation = "https://github.com/zuiyue-com/wei-log"
homepage = "https://github.com/zuiyue-com/wei-log"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4.26"
